name: homemakercompanion
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.0
  intro_views_flutter: ^2.8.0
  wave: ^0.0.8
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.4.1
  shared_preferences: ^0.5.6
  bottomreveal: ^1.0.0
  charts_flutter: ^0.8.0
  animated_floatactionbuttons: ^0.1.0
  share: ^0.6.3+5
  intl: ^0.16.0
  flare_flutter: ^1.8.3
  provider: ^3.2.0
  cached_network_image: ^2.0.0
  package_info: ^0.4.0+13
  firebase_remote_config: ^0.3.0+1
  firebase_analytics: ^5.0.9
  flutter_staggered_grid_view: ^0.3.0
  crop: ^0.1.2
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  google_sign_in: ^4.5.0
  image_picker: ^0.6.6+4
  firebase_storage: ^3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  flutter_automation:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/app-store-logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/smwallet/
    - assets/hotel/
    - assets/icon/
    - assets/flare/
    - assets/nicasiaassets/
    - assets/image_01.png
    - assets/image_02.jpg
    - assets/image_03.jpg
    - assets/image_04.jpg

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf


    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf


    - family: Niconne
      fonts:
        - asset: fonts/Niconne-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons.ttf

